In [1]:
import numpy as np
# numpy is numerical python

In [2]:
# numpy is similar to lists
# numpy much faster than lists
# numpy stores same data type and lists stores different data type

In [6]:
# one dimension array
a = np.array([5,5,5,])
a

array([5, 5, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
# two dimension array
b = np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#### 1 dimension array is called VECTOR
#### 2 dimension array is called MATRIX

#### 3 dimensional or higher array is called TENSOR

##### Dimesions are called AXIS

In [10]:
# zero array
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [11]:
# ones array
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [12]:
# empty array
empty = np.empty(3)
empty

array([1.10279994e-311, 0.00000000e+000, 2.37663593e-312])

### Create an array with arange() function

In [13]:
# with range of elements
e = np.arange(30)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
# giving sepcific range
f = np.arange(20, 60)
f

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

In [18]:
# continue - giving gap
h = np.arange(20,100,20)
h

array([20, 40, 60, 80])

In [22]:
# linerly spaced arrays
# it makes array with 'num' spaced values between two ranges
g = np.linspace(5,20,num=6)
g

array([ 5.,  8., 11., 14., 17., 20.])

## Giving specific data types in array

In [24]:
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [25]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

## 2D Array

In [27]:
k = np.ones((3,4), dtype=np.int8)
k

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [28]:
l = np.ones((5,6), dtype=np.float64)
l

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [46]:
n = np.array([[1,2,3,4,5],[6,7,8,9,10]])
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
o = np.array([[4,5],[6,7]])
o

array([[4, 5],
       [6, 7]])

In [49]:
# Concatenating 2-D Array if dimensions are not same
p = np.column_stack((o,n))
p

array([[ 4,  5,  1,  2,  3,  4,  5],
       [ 6,  7,  6,  7,  8,  9, 10]])

In [50]:
q = np.array([[4,5],[6,7]])
q

array([[4, 5],
       [6, 7]])

In [51]:
r = np.array([[2,3],[23,34]])
r

array([[ 2,  3],
       [23, 34]])

In [52]:
s = np.concatenate((q,r) , axis=0)
s

array([[ 4,  5],
       [ 6,  7],
       [ 2,  3],
       [23, 34]])

In [53]:
s = np.concatenate((q,r) , axis=1)
s

array([[ 4,  5,  2,  3],
       [ 6,  7, 23, 34]])

## 3-D Array

In [32]:
m = np.arange(24).reshape(2,3,4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
t = np.array([
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]],
    [[0,1,2,3],[4,5,6,7]]
])
t

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [59]:
# to find the dimension of arrays
t.ndim

3

In [56]:
u = np.array([
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
u

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
u.ndim

2

In [60]:
# size = number of elements
t.size

24

In [61]:
# shape
t.shape

(3, 2, 4)

In [33]:
a = np.array([3,43,22,43,20,0.4,100,324])
a

array([  3. ,  43. ,  22. ,  43. ,  20. ,   0.4, 100. , 324. ])

In [35]:
a.sort()
a

array([  0.4,   3. ,  20. ,  22. ,  43. ,  43. , 100. , 324. ])

In [36]:
b = np.array([5.65,345,534,67.34,54])
b

array([  5.65, 345.  , 534.  ,  67.34,  54.  ])

In [37]:
b.sort()
b

array([  5.65,  54.  ,  67.34, 345.  , 534.  ])

In [38]:
c = np.concatenate((a,b))
c

array([4.000e-01, 3.000e+00, 2.000e+01, 2.200e+01, 4.300e+01, 4.300e+01,
       1.000e+02, 3.240e+02, 5.650e+00, 5.400e+01, 6.734e+01, 3.450e+02,
       5.340e+02])

In [67]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
# 3x3 = 9 so the a has 9 elements and 3x3 will reshape it to 2-D array
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
# reshape
np.reshape(a, newshape=(1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [71]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [72]:
a+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
a.sum()

36

In [74]:
a.mean()

4.0

## You can use it in VS CODE

### All you need is Python and Jupyter Extension